"""add ai_report column

Revision ID: 90cab8a03411
Revises: 6b0cab6609ef
Create Date: 2026-04-13 18:53:43.359223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cab8a03411'
down_revision: Union[str, Sequence[str], None] = '6b0cab6609ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('ai_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'ai_report')
    # ### end Alembic commands ###
